# Config file for use with the following logs on Security Onion
# - Windows logs shipped with Winlogbeat
# - Osquery logs shipped with the SO/osquery integrated configs 
title: SO configs
logsources:
  osquery:
    product: osquery
    index: so-osquery-*
  windows:
    product: windows
    index: so-*
  windows-application:
    product: windows
    service: application
    conditions:
      log_name: Application
  windows-security:
    product: windows
    service: security
    conditions:
      log_name: Security
  windows-sysmon:
    product: windows
    service: sysmon
    conditions:
      log_name: 'Microsoft-Windows-Sysmon/Operational'
  windows-dns-server:
    product: windows
    service: dns-server
    conditions:
      log_name: 'DNS Server'
  windows-driver-framework:
    product: windows
    service: driver-framework
    conditions:
      source: 'Microsoft-Windows-DriverFrameworks-UserMode/Operational'
defaultindex: so-*
fieldmappings:
    EventID: event.code
    log_name: event.dataset
    AccessMask: event_data.AccessMask
    AccountName: event_data.AccountName
    AllowedToDelegateTo: event_data.AllowedToDelegateTo
    AttributeLDAPDisplayName: event_data.AttributeLDAPDisplayName
    AuditPolicyChanges: event_data.AuditPolicyChanges
    AuthenticationPackageName: event_data.AuthenticationPackageName
    CallingProcessName: event_data.CallingProcessName
    CallTrace: event_data.CallTrace
    CommandLine: process.command_line
    Company: event_data.Company
    ComputerName: event_data.ComputerName
    CurrentDirectory: process.working_directory"
    Description: process.pe.description
    DestinationHostname: event_data.DestinationHostname
    DestinationIp: destination_ip
    DestinationIsIpv6: event_data.DestinationIsIpv6
    DestinationPort: destination_port
    Details: event_data.Details
    EngineVersion: event_data.EngineVersion
    EventType: event_data.EventType
    FailureCode: event_data.FailureCode
    FileName: event_data.FileName
    FileVersion: event_data.FileVersion
    GrantedAccess: event_data.GrantedAccess
    GroupName: event_data.GroupName
    Hashes: event_data.Hashes
    HiveName: event_data.HiveName
    HostVersion: event_data.HostVersion
    Image: process.executable
    ImageLoaded: event_data.ImageLoaded
    ImagePath: event_data.ImagePath
    Imphash: event_data.Imphash
    Initiated: event_data.Initiated
    LogonProcessName: event_data.LogonProcessName
    LogonType: event_data.LogonType
    NewProcessName: event_data.NewProcessName
    ObjectClass: event_data.ObjectClass
    ObjectName: event_data.ObjectName
    ObjectType: event_data.ObjectType
    ObjectValueName: event_data.ObjectValueName
    ParentCommandLine: process.parent.command_line
    ParentImage: process.parent.executable
    Path: event_data.Path
    PipeName: event_data.PipeName
    ProcessName: event_data.ProcessName
    Properties: event_data.Properties
    ServiceFileName: event_data.ServiceFileName
    ServiceName: event_data.ServiceName
    ShareName: event_data.ShareName
    Signature: event_data.Signature
    Source: event_data.Source
    SourceImage: event_data.SourceImage
    StartModule: event_data.StartModule
    Status: event_data.Status
    SubjectUserName: event_data.SubjectUserName
    TargetFilename: event_data.TargetFilename
    TargetImage: event_data.TargetImage
    TargetObject: event_data.TargetObject
    TicketEncryptionType: event_data.TicketEncryptionType
    TicketOptions: event_data.TicketOptions
    User: event_data.User
    WorkstationName: event_data.WorkstationName
    Product: process.pe.product
    GroupSid: event_data.GroupSid    
    RelativeTargetName: event_data.RelativeTargetName
    qid: osquery.columns.qid
    hostname: osquery.result.hostname
    counter: osquery.result.counter
    column_name: osquery.columns.name
    query_name: osquery.result.name
    username: user.name
    uid: user.uid
